"""identity resolution: company_sources, normalized fields, dedup constraints

Revision ID: 5ccaaffd2b6d
Revises: 531c7e1034ad
Create Date: 2026-09-11 16:09:36.228167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ccaaffd2b6d'
down_revision: Union[str, None] = '531c7e1034ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_sources',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('company_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('source_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source_id', name='uq_company_source')
    )
    op.add_column('addresses', sa.Column('normalized_address', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_addresses_normalized_address'), 'addresses', ['normalized_address'], unique=False)
    op.add_column('companies', sa.Column('normalized_city', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_companies_normalized_city'), 'companies', ['normalized_city'], unique=False)
    op.create_index('ix_companies_normalized_name_city', 'companies', ['normalized_name', 'normalized_city'], unique=False)
    op.create_unique_constraint('uq_company_email', 'company_emails', ['company_id', 'email'])
    op.create_unique_constraint('uq_company_phone_normalized', 'company_phones', ['company_id', 'phone_normalized'])
    op.create_unique_constraint('uq_company_website_domain', 'company_websites', ['company_id', 'domain'])
    op.add_column('social_links', sa.Column('url_fingerprint', mysql.CHAR(length=64), nullable=False))
    op.create_unique_constraint('uq_company_social_platform_url', 'social_links', ['company_id', 'platform', 'url_fingerprint'])
    op.create_index('ix_sources_type_external_id', 'sources', ['source_type', 'external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sources_type_external_id', table_name='sources')
    op.drop_constraint('uq_company_social_platform_url', 'social_links', type_='unique')
    op.drop_column('social_links', 'url_fingerprint')
    op.drop_constraint('uq_company_website_domain', 'company_websites', type_='unique')
    op.drop_constraint('uq_company_phone_normalized', 'company_phones', type_='unique')
    op.drop_constraint('uq_company_email', 'company_emails', type_='unique')
    op.drop_index('ix_companies_normalized_name_city', table_name='companies')
    op.drop_index(op.f('ix_companies_normalized_city'), table_name='companies')
    op.drop_column('companies', 'normalized_city')
    op.drop_index(op.f('ix_addresses_normalized_address'), table_name='addresses')
    op.drop_column('addresses', 'normalized_address')
    op.drop_table('company_sources')
    # ### end Alembic commands ###
