"""job_run_companies scope table for export

Revision ID: 91b3235d611b
Revises: a1f786f27f5b
Create Date: 2026-09-14 08:39:17.824096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91b3235d611b'
down_revision: Union[str, None] = 'a1f786f27f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_run_companies',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('job_run_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('company_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('resolution', sa.Enum('new', 'matched', name='jobruncompanyresolution', native_enum=False, length=20), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_run_id', 'company_id', name='uq_job_run_company')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_run_companies')
    # ### end Alembic commands ###
