"""job orchestration: JobRun, JobStageRun, Job config fields

Revision ID: a1f786f27f5b
Revises: 24dbc667ca6f
Create Date: 2026-09-11 17:00:36.019144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a1f786f27f5b'
down_revision: Union[str, None] = '24dbc667ca6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('job_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('created', 'running', 'paused', 'completed', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('current_stage', sa.Enum('created', 'discovery_osm', 'discovery_web_search', 'normalization', 'identity_resolution', 'website_enrichment', 'finalizing', 'completed', 'failed', 'cancelled', name='pipelinestage', native_enum=False, length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_stage_runs',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('job_run_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('stage', sa.Enum('created', 'discovery_osm', 'discovery_web_search', 'normalization', 'identity_resolution', 'website_enrichment', 'finalizing', 'completed', 'failed', 'cancelled', name='pipelinestage', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', name='stagestatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('input_count', sa.Integer(), nullable=True),
    sa.Column('output_count', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('preset', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('regions', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('sources_config', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('source_limits', sa.JSON(), nullable=True))
    op.add_column(
        'jobs',
        sa.Column('website_enrichment', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'website_enrichment')
    op.drop_column('jobs', 'source_limits')
    op.drop_column('jobs', 'sources_config')
    op.drop_column('jobs', 'regions')
    op.drop_column('jobs', 'preset')
    op.drop_table('job_stage_runs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
