"""initial schema

Revision ID: c12e08024a2d
Revises: 
Create Date: 2026-09-11 14:57:05.922543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c12e08024a2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=False)
    op.create_table('jobs',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('created', 'running', 'paused', 'completed', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('requested_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('source_type', sa.Enum('google_maps', 'google_search', 'website', 'directory', 'manual', 'other', name='sourcetype', native_enum=False, length=20), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('job_id', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('company_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=500), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('raw_address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('source_id', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_emails',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('company_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('source_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_emails_email'), 'company_emails', ['email'], unique=False)
    op.create_table('company_phones',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('company_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('phone_raw', sa.String(length=50), nullable=False),
    sa.Column('phone_normalized', sa.String(length=30), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('source_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_phones_phone_normalized'), 'company_phones', ['phone_normalized'], unique=False)
    op.create_table('company_websites',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('company_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('source_id', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_websites_domain'), 'company_websites', ['domain'], unique=False)
    op.create_table('raw_records',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('job_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('source_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_links',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('company_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'telegram', 'linkedin', 'youtube', 'tiktok', 'other', name='socialplatform', native_enum=False, length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source_id', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_links')
    op.drop_table('raw_records')
    op.drop_index(op.f('ix_company_websites_domain'), table_name='company_websites')
    op.drop_table('company_websites')
    op.drop_index(op.f('ix_company_phones_phone_normalized'), table_name='company_phones')
    op.drop_table('company_phones')
    op.drop_index(op.f('ix_company_emails_email'), table_name='company_emails')
    op.drop_table('company_emails')
    op.drop_table('addresses')
    op.drop_table('sources')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
